#!/bin/sh

# directories
export codebin=${codebin-../bin/}
export genbin=${genbin-../bin/}
export results=${results-../results/}

# parameters
export numruns=${numruns-1}
export numseeds=${numseeds-5}
export startseed=${startseed-3141}
export seedincr=${seedincr-10}

./rmf-long $*
./rmf-longer $*
./rmf-wide $* 
./wash-rlg-long $*
./wash-rlg-wide $*
./wash-line-moderate $*
./ac-dense $*
./ak $*	  	    
